Add Driving innovation, Who we are?, Services and Team sections
walnut-venture/website pull request #2
Opened 2023-07-04 18:13 UTC by Grappler2010

2023-07-04 22:50 UTC, dealwith requested changes
The PR is good, but you didn't integrate the CMS, please integrate it first

2023-07-04 22:50 UTC, dealwith commented on app/components/ServicesSection/ServicesSection.tsx
> +              <P className={styles.number}>01.</P>
should be semantically `ul > li`, I guess

2023-07-04 22:50 UTC, dealwith commented on app/components/DrivingInnovationSection/DrivingInnovationSection.tsx
> +          <Image className={styles.image} src={imageSrc} alt="Image" />
These images shouldn't come from src, they should come from contentful CMS, please add images to Contentful

2023-07-04 23:03 UTC, dealwith approved these changes

2023-07-04 23:04 UTC, dealwith commented
Forget about CMS comment above, I will first discuss it with Julian

2023-07-05 11:01 UTC, Grappler2010 commented on app/components/ServicesSection/ServicesSection.tsx
> +              <P className={styles.number}>01.</P>
Maybe we will change them to components in the future

2023-07-05 11:01 UTC, merged